name: meals_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/italian.png
    - assets/spaghetti.png
    - assets/quickeasy.png
    - assets/hamburgers.png
    - assets/german.png
    - assets/lightlovely.png
    - assets/exotic.png
    - assets/breakfast.png
    - assets/asian.png
    - assets/french.png
    - assets/summer.png
