name: meals_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/category_meals_pictures/italian.png
    - assets/category_meals_pictures/spaghetti.png
    - assets/category_meals_pictures/quickeasy.png
    - assets/category_meals_pictures/hamburgers.png
    - assets/category_meals_pictures/german.png
    - assets/category_meals_pictures/lightlovely.png
    - assets/category_meals_pictures/exotic.png
    - assets/category_meals_pictures/breakfast.png
    - assets/category_meals_pictures/asian.png
    - assets/category_meals_pictures/french.png
    - assets/category_meals_pictures/summer.png
    - assets/detailed_meals_pictures/spaghettiwithtomatosouce.png
    - assets/detailed_meals_pictures/toasthawaii.png
    - assets/detailed_meals_pictures/classichamburger.png
    - assets/detailed_meals_pictures/wienerschnitzel.png
    - assets/detailed_meals_pictures/saladwithsalmon.png
    - assets/detailed_meals_pictures/deliciousorangemousse.png
    - assets/detailed_meals_pictures/pancakes.png
    - assets/detailed_meals_pictures/indianchickencurry.png
    - assets/detailed_meals_pictures/chocolatesouffle.png
    - assets/detailed_meals_pictures/grilledasparagussalad.png
    - assets/real_meals_pictures/spaghettiwithtomatosouce.png
    - assets/real_meals_pictures/toasthawaii.png
    - assets/real_meals_pictures/classichamburger.png
    - assets/real_meals_pictures/wienerschnitzel.png
    - assets/real_meals_pictures/saladwithsmokedsalmon.png
    - assets/real_meals_pictures/orangemousse.png
    - assets/real_meals_pictures/pancakes.png
    - assets/real_meals_pictures/creamyindianchickencurry.png
    - assets/real_meals_pictures/chocolatesouffle.png
    - assets/real_meals_pictures/grilledasparagussalad.png

